config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :tasks,          except: [:index]
  
  root 'static_pages#home'
  

  get 'help' => 'static_pages#help'
  
  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates_presence_of :title
  validate :future_completed_date

  private

    def future_completed_date
      if !completed.blank? && completed > Date.today
        self.errors.add(:completed, "can't be in the future")
      end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy, :edit, :update]
  before_action :correct_user,   only: [:destroy, :edit, :update]

  def new
    @task = current_user.tasks.build
    render :show_form
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "New task added!"
      redirect_to root_url
    else
      @feed_items = []
      redirect_to root_url
    end
  end

  def destroy
    @task.destroy
    flash[:success] = "Task deleted"
    redirect_to request.referrer || root_url
  end

  def edit
    @task = Task.find(params[:id])
    render :show_form
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    if @task.save
      flash[:success] = "Task updated!"
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  private
  
    def task_params
      params.require(:task).permit(:title, :content, :completed)
    end

    def correct_user
      @task = current_user.tasks.find_by(id: params[:id])
      redirect_to root_url if @task.nil?
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.html.erb
<div class="container">
  <% if current_user.tasks.any? %>
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Created at</th>
        <th>Completed</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong>
          <li id="task-<%= task.id %>">
            <%= task.title %>
          </li>
        </strong></td>
        <td class="text-info">
          <%= task.created_at %>
        </td>
        <td class="text-success">
          <%= task.completed %>
        </td>
        <td>
          <% if current_user?(task.user) %>
            <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?"} do %>
              <i class="glyphicon glyphicon-remove"></i>
            <% end %>
            <%= link_to edit_task_path(task), remote: true do %>
              <i class="glyphicon glyphicon-edit"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <% else %>
  <span class="text-warning">There are no tasks!</span>
  <% end %>
</div>

app/views/tasks/_task_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h1>
        <%= task.new_record? ? 'New Task' : "Editing task" %>
      </h1>
    </div>
    <%= simple_form_for task, class: 'clearfix' do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="modal-body">
      <%= f.input :title %>
      <%= f.input :content %>
      <%= f.input :completed, as: :string, input_html: { class: 'datepicker', value: task.completed.present? ? localize(task.completed, format: '%d/%m/%Y') : nil } %>
    </div>
    <div class="modal-footer">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
</div>

app/views/tasks/show_form.js.erb
$('#modal').html('<%= j(render partial: 'task_form', locals: {task: @task}) %>').modal('show');

$('#modal').integrateDatepicker();